name: App-Build

on:
  push:
    branches: [ main ]
    paths: 
        - "src/**"
        - ".github/workflows/app_build.yml"
  pull_request:
    branches: [ main ]
    paths: 
        - "src/**"
        - ".github/workflows/app_build.yml"

defaults:
  run:
    working-directory: "src/Sytko.Blazor.EditorDemo/"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@main

    - name: Install Dotnet 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100-preview.2'

    - name: Build App...
      run: |
        cd ${{ github.workspace }}/src/Sytko.Blazor.EditorDemo
        dotnet restore
        dotnet publish -c Release -o '${{ github.workspace }}/App' 

    - name: Create Zip
      run: |
        cd ${{ github.workspace }}/App
        zip -r "${{ github.workspace }}/blazor_editor.zip" .

    - name: Cleanup remote directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script_stop: true
        script: |
          rm -r /opt/docker/project/blazor_test/http/*

    - name: Transfer app...
      uses: garygrossgarten/github-action-scp@release
      with:
        local: "${{ github.workspace }}/blazor_editor.zip"
        remote: "/opt/docker/project/blazor_test/http/blazor_editor.zip"
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        privateKey : ${{ secrets.SSH_KEY }}

    - name: Extract app...
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script_stop: true
        script: |
          unzip /opt/docker/project/blazor_test/http/blazor_editor.zip -d /opt/docker/project/blazor_test/http/